# Generated by Django 3.2.3 on 2021-05-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=25)),
                ('car_model', models.CharField(max_length=40)),
                ('car_gen', models.CharField(max_length=10)),
                ('car_year', models.CharField(max_length=4)),
            ],
        ),
    ]
